# _config.yml
markdown: kramdown
url: "https://fabriziomiano.com"
baseurl: ""
repository: fabriziomiano/fabriziomiano.github.io
plugins:
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - bin
  - .devcontainer
